climate-action-kits/pxt-fwd-edu

treeseeder.md
changed servo2 to servo1
servo1 and servo3 for driving
servo2 for dropping seeds
=> updated tree seeder tutorial

motm-line.md, motm-obs.md, pxt.json
motm-line and motm-obs tutorial
updated pxt.json
=> 2 tutorials for motm added

wind-gr-5-lesson.md
added tutorial assets with low resolutions
changed couple of steps and added new steps
=> urgent request to update and publish

windenergy.md
made this change to match with the building instructions.
=> changed leftServo to rightServo

wind-gr-5-lesson.md
this is updated with new coding steps. this tutorial underwent major changes as the whole coding activity was changed
=> wind-gr-5-lesson tutorial major revamp

treeseeder.md, wind-gr-5-lesson.md
*.gif to *.png and vice versa
wrong filename used
=> removed typos and fixed file extensions

pxt.json, wind-power-storage.md
-added the a new tutorial file
-added file to pxt.json
=> Wind Lesson 2 tutorial

wind-gr-5-lesson.md, wind-power-storage.md
-label change as per new building instructions. 
-urgent push as translations started
=> changed rightServo to middleServo

bees-5-6.md, plantsnpollinators.md
-added new steps
-added new gifs-images
=> Plants-Pollinators-both-tutorials-updated

adv-agri-5-6-a.md, adv-agri-7-8-a.md, advancedagriculture.md
-changed title
-added new steps
-block referencing for LED color changed
=> 3x Smart Farming Tutorials Update

wind-gr-6-lesson.md, windenergy.md
-duplicated a tutorial for alignment with a bit.ly link generated which is used at conferences/events
-changed servo assignment to middleServo
-changed call to action for steps which seemed to be a duplicate of a previous step
=> Wind Energy Tutorials Updates

_locales/fr/wind-gr-5-lesson.md, _locales/fr/wind-power-storage.md
-title changed to fr
-block names changed to fr
=> wind#1-#2 title and blocks text updated with fr

wind-gr-6-lesson.md
-major changes to steps
-changed from RPM calculation to a stop watch based activity
=> wind#3 revised tutorial activity

ev-obstacle-py.md
- added buttons to initiate the movement after code is downloaded
- button a to run the code
- button b to stop the code
- sonar to detect obstacle, avoid and go around in a forever loop
=> EV python button activated tutorial

_locales/es/wind-gr-5-lesson.md, _locales/es/wind-power-storage.md, lesson-final-code/advagri-1-code.md, lesson-final-code/advagri-1-ext.md, lesson-final-code/advagri-2-code.md, lesson-final-code/advagri-2-ext.md, lesson-final-code/advagri-3-code.md, lesson-final-code/advagri-3-ext.md, lesson-final-code/ev-obstacle-code.md, lesson-final-code/plants-1-code.md, lesson-final-code/plants-1-ext.md, lesson-final-code/plants-2-code.md, lesson-final-code/plants-2-ext.md, lesson-final-code/solar-code.md, lesson-final-code/solar-ext.md, lesson-final-code/tree-seeder-code.md, lesson-final-code/tree-seeder-ext.md, lesson-final-code/wind-1-ext.md, lesson-final-code/wind-2-ext.md
-wind#1 and #2 Spanish Tutorial files
-17 files added to the lesson-final-code folder. 
-all the share links have been transformed
-all these files need to be added to pxt.json
=> Spanish tutorial, coding & extension activities

_locales/fr/wind-gr-6-lesson.md
=> wind#3 french tutorial

ev-wildfire.md
-final v1 tutorial of electric vehicles-wildfire lesson
=> new ev wildfire tutorial

ev-wildfire.md, lesson-final-code/ev-wildfire-code.md, lesson-final-code/ev-wildfire-ext.md, pxt.json
-tutorial coding activity updated
-final code added as a template
-ext code added as a template
-pxt.json updated with filenames
=> wildfire lesson updates

adv-agri-7-8-a.md, solarenergy.md
=> Brenden feedback chages

robo-delivery-11-12.md
* Updating
fixed error in step 9
* changed the title to match the new title
* Fixed typo in step 24
* fixed type in step 7
* added hint to step 6
* updated hint on step 7
* Updated hint in step 8
* added hint to step 9
* Added hint to step 10
* Added hint to step 12
* added hint to step 14
* Added hint to step 17
* Added hint to step 18
* added hint to step 19
* Added hint to step 20
* hint in step 21
* Hint added to step 22
* Added hint to step 24
* Added hint to step 25
* Updated hint in step 31
* Update hint in step 35
=> Added the hint feature to all of the steps 

Windtrial
* Create Windtrial 
New tutorial for the trial l lesson for Powering the Future with Wind energy
* Adding hint to step 9 
Added hint
* Added hint to step10
* Added hint to step 11
* Added hint to step 12
* Added hint to step 13
* Remove step 14
* Removed step 15
* Added hint to step 16
* Added hint to step 17
* edited step 8
* Edited step 9 hint feature
* \updated hint step 13
* Updated step 19
* Removed image from step 19 it is out of date
* removed step 20 and updated steps accordingly
* Changed the title
* updated working in step 6
* Updated working in step 7
* Changed title
=> Created new tutorial for wind 1 that is more simple for demos

gr6-glaciers-modify, pxt.json
* Created gr6-glaciers-modify with package and activity 1
* added started code template
* added new glaciers lessons to pxt
=> Jessica forwardedu patch 1 (#16)

gr11-electriccar-modify.md, gr11-electriccar-use.md
fixing electric vehicle tutorials
=> Jessica forwardedu patch 1 

gr11-electriccar-modify.md, gr11-electriccar-use.md
* Fixing more of my typos 
* Update gr11-electriccar-use.md
* Update gr11-electriccar-modify.md
* fixed typo
* fixed typos
=> Jessica forwardedu patch 1 (#21)

gr68-turtles-modify.md, gr68-turtles-use.md, pxt.json
* Created gr68-turtles-use.md
* Added all building steps w images
* Added activity 2 coding \
* Added Use step 1 and 2
* Added use step 6-8
* Added use step 9 8 and outro steps
* Added gr68-turtles-use.md
* Create gr68-turtles-modify.md
* added all the building steps
* Added coding step up steps
* Added use step 1-3
* Added All use steps
* Added Challenge step 1 and 2
* Challenge step three
* Add challenge steps and outro
* Update pxt.json with gr68-turtles-modify.md
=> Jessica forwardedu patch 1 (#22)

ms-sodis-modify.md, ms-sodis-use.md, pxt.json
Two new UMC tutorials for the SODIS project.
=> SODIS UMC tutorial update

ms-sodis-modify.md
Clarified language to be more accurate.
=> Fixed small error in 'Challenge Step 13'

gr8-smartfarming-modify.md, gr9-treeSeeder-use.md, gr9-verticalfarm-modify.md, ms-sodis-modify.md
Smart farming, sodis, vertical farming, and tree seeder lessons 🌱
=> Updated wording and lesson formatting

hs-fishways-modify.md, hs-fishways-use.md
Updating use & modify tutorials to include steps for learners
=> Fishways completed use & modify tutorial

es-risingfloodalarm-modify.md, es-risingfloodalarm-use.md, hs-fishways-use.md, ms-aquaticgarbage-modify.md, ms-aquaticgarbage-use.md
Preliminary feedback updates to flood alarms project.
=> Early release garbage collection project 🚛

es-risingfloodalarm-modify.md, es-risingfloodalarm-use.md, hs-autodelivery-modify.md, hs-autodelivery-use.md, hs-fishways-modify.md, hs-fishways-use.md, ms-aquaticgarbage-modify.md, ms-aquaticgarbage-use.md, ms-risingsea-modify.md, ms-risingsea-use.md, ms-smarthome-modify.md, ms-smarthome-use.md, pxt.json
Created early release tutorials (renders to come) for: 
- Smart Home Use
- Smart Home Modify
Edited syntax for Makecode tutorials for: 
- Rising sea level
- Flood alarm
- Fishways
- Aquatic garbage collector
- Warehouse robot
=> Smart Home U & M 🏠, Syntax updates 

ms-risingsea-use.md, ms-smarthome-modify.md, ms-smarthome-use.md
Removed placeholder images in Use and Modify tutorials for smart home project, edited minor formatting errors due to Makecode on coastal flooding lesson
=> Rising Sea formatting, Smart Home placeholder removed

gr8-smartfarming-modify.md, gr8-smartfarming-use.md
Set moisture threshold to 20%.
Increased pause between pump runs from 500 ms to 1000 ms.
=> Updated started code slightly to improve functionality of pump.
